# -*- coding: utf-8 -*-
"""graphAgeWithSeq_3.5 cross validation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q7yC3zNsLcL9CYHAjn0k-9KJskKgiD2p
"""

# Spartan环境已预装torch_geometric，无需安装
# （原Colab代码：!pip install torch_geometric）
# （原Colab代码：from google.colab import drive; drive.mount('/content/drive')）

# ============================================================
# Cell 0-2: 导入所有库
# ============================================================

import os
import random

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split, KFold, ParameterGrid
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import (
    mean_squared_error,
    mean_absolute_error,
    r2_score,
    median_absolute_error
)

from scipy.spatial.distance import pdist, squareform
from tqdm import tqdm

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.nn import Linear, ModuleList
from torch.optim.lr_scheduler import ReduceLROnPlateau

from torch_geometric.data import Data
from torch_geometric.loader import DataLoader
from torch_geometric.nn import BatchNorm, PNAConv


# ============================================================
# 随机种子（统一版本）
# ============================================================

random_seed = 0
random.seed(random_seed)
np.random.seed(random_seed)
torch.manual_seed(random_seed)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(random_seed)


# ============================================================
# 设备
# ============================================================

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")
print(f"PyTorch version: {torch.__version__}")
print("库导入完成！")

# ============================================================
# Cell 0-3: 加载和预处理CpG位点信息
# ============================================================

# 文件路径
file_path = "/data/projects/punim2698/yao14/graphage_seq/cpgsite-info/GPL8490_HumanMethylation27_270596_v.1.2.csv"

# 读取CSV文件（跳过前7行）
information = pd.read_csv(file_path, skiprows=7, low_memory=False)

# 删除没有染色体信息的行
information.dropna(subset=['Chr'], inplace=True)

# 处理CpG岛位置信息
information[["start", "end"]] = information.CPG_ISLAND_LOCATIONS.fillna("0:0-0").str.split(':').str[1].str.split('-', expand=True).astype(int)
information['CPG_ISLAND'] = information['CPG_ISLAND'].astype(int)

information["CPG_ISLAND_LEN"] = information.end - information.start
information.groupby('Chr')['MapInfo'].max().sort_values(ascending=False)
information.MapInfo = information.MapInfo.astype(int)

information.groupby('Chr')['MapInfo'].min().sort_values(ascending=False)

# 归一化处理
scaler = MinMaxScaler()
information['Normalized_MapInfo'] = information.groupby('Chr')['MapInfo'].transform(
    lambda x: scaler.fit_transform(x.values.reshape(-1, 1)).flatten()
)
information['Normalized_TSS_Coordinate'] = information.groupby('Chr')['TSS_Coordinate'].transform(
    lambda x: scaler.fit_transform(x.values.reshape(-1, 1)).flatten()
)

# One-Hot编码 - Gene_Strand
information = pd.get_dummies(information, columns=["Gene_Strand"])

# 归一化 start, end, CPG_ISLAND_LEN
information['start'] = information.groupby('Chr')['start'].transform(
    lambda x: scaler.fit_transform(x.values.reshape(-1, 1)).flatten()
)
information['end'] = information.groupby('Chr')['end'].transform(
    lambda x: scaler.fit_transform(x.values.reshape(-1, 1)).flatten()
)
information['CPG_ISLAND_LEN'] = information.groupby('Chr')['CPG_ISLAND_LEN'].transform(
    lambda x: scaler.fit_transform(x.values.reshape(-1, 1)).flatten()
)

# One-Hot编码 - Next_Base
information = pd.get_dummies(information, columns=["Next_Base"])

# 处理Distance_to_TSS
information.Distance_to_TSS.fillna(float("inf"))
information['Distance_to_TSS'] = information.groupby('Chr')['Distance_to_TSS'].transform(
    lambda x: scaler.fit_transform(x.values.reshape(-1, 1)).flatten()
)
information['Distance_to_TSS'] = information['Distance_to_TSS'].fillna(1)

# One-Hot编码 -
information = pd.get_dummies(information, columns=["SourceStrand"])

# 保存Chr列，然后One-Hot编码
Chrom = information.Chr.tolist()
information = pd.get_dummies(information, columns=["Chr"])
information['Chr'] = Chrom

# 设置索引
information.index = information.IlmnID

# 原始代码中的columns_to_add
columns_to_add = ["start", "end", "SourceStrand_TOP", "SourceStrand_BOT", "Normalized_MapInfo",
                  "Gene_Strand_+", "Gene_Strand_-", "CPG_ISLAND_LEN", "Next_Base_A", "Next_Base_C",
                  "Next_Base_T", "Distance_to_TSS"]

print(f"information形状: {information.shape}")
print(f"columns_to_add: {columns_to_add}")
print("CpG位点信息预处理完成！")

# ============================================================
# Cell 0-4: 定义阈值、函数和特征选择
# ============================================================

# 阈值设置（与原始代码第155-158行一致）
THRESHOLD_DIST = 1e5
THRESHOLD_CORR = 0.70        # 实验验证0.70效果最好
SECONDARY_THRESHOLD = THRESHOLD_CORR - 0.02  # 0.73
TERTIARY_THRESHOLD = THRESHOLD_CORR - 0.04   # 0.71

EDGE_DIM = 4   # 原来是3，新增第4维：同CpG岛标记

# CpG位点注释文件路径（用于提取CPG_ISLAND_LOCATIONS）
CPG_INFO_PATH = '/data/projects/punim2698/yao14/graphage_seq/cpgsite-info/GPL8490_HumanMethylation27_270596_v.1.2.csv'

# make_cpg2node函数（与原始代码第133-148行一致）
node2cpg = {}
def make_cpg2node(cpg):
    """
    Create a mapping from CpG names to node indices.
    """
    cpg2node = {}
    for i, c in enumerate(cpg):
        cpg2node[c] = i
        node2cpg[i] = c
    return cpg2node

# make_graph函数
# 方案：不新增边，只给现有边打同CpG岛标记（第4维）
# 同CpG岛 = 两个位点在同一个CpG岛内，受同一启动子调控
# 保证所有边都有共甲基化信号支撑，PNA层不会崩溃
def make_graph(information, threshold_corr, threshold_dist, meth, cpg2node, chromosomes):
    src = []
    dst = []
    weights = []

    chromosomes = information.Chr.values
    genes = information.Symbol.values

    # 同染色体邻接矩阵
    print('makeing same chromo adjacency...')
    chromosomes = np.array(chromosomes)
    chromosome_adj = (chromosomes[:, None] == chromosomes).astype(np.float32)

    # 距离矩阵
    print('making distance matrix .......')
    base_pair = information.MapInfo.values
    pairwise_distances = pdist(base_pair.reshape(-1, 1))
    distance_matrix = squareform(pairwise_distances)

    # 同基因邻接矩阵
    print('makeing same gene adjacency...')
    genes = np.array(genes)
    genes_adj = (genes[:, None] == genes).astype(np.float32)

    # 共甲基化相关性矩阵
    print('makeing comethylation adjacency...')
    adj = np.corrcoef(meth.to_numpy(), rowvar=False)

    # ── 新增：同CpG岛邻接矩阵（给现有边打标记，不新增边）──
    # 两个位点在同一个CpG岛内 → 第4维 = 1.0，否则 = 0.0
    # 生物学意义：同CpG岛的位点受同一启动子调控，
    #             在衰老过程中倾向于协同甲基化变化
    print('making same CpG island label matrix...')
    n = len(information)
    same_island_adj = np.zeros((n, n), dtype=np.float32)
    try:
        # 从information里提取CpG岛位置信息
        island_locations = information['CPG_ISLAND_LOCATIONS'].values

        # 建立CpG岛位置 → 位点索引列表的映射
        island_to_indices = {}
        for idx, loc in enumerate(island_locations):
            if pd.notna(loc) and str(loc).strip() != '':
                loc_str = str(loc).strip()
                if loc_str not in island_to_indices:
                    island_to_indices[loc_str] = []
                island_to_indices[loc_str].append(idx)

        # 同一CpG岛内的所有位点对互相标记
        island_pairs = 0
        for loc, indices in island_to_indices.items():
            if len(indices) >= 2:
                for i in range(len(indices)):
                    for j in range(i + 1, len(indices)):
                        ii, jj = indices[i], indices[j]
                        same_island_adj[ii, jj] = 1.0
                        same_island_adj[jj, ii] = 1.0
                        island_pairs += 1

        nonzero = int(np.count_nonzero(same_island_adj))
        multi_island_count = sum(1 for v in island_to_indices.values() if len(v) >= 2)
        print(f'  共处理 {len(island_to_indices)} 个CpG岛')
        print(f'  有多个位点的CpG岛: {multi_island_count} 个')
        print(f'  同CpG岛位点对: {island_pairs:,} 对（单向）')
        print(f'  same_island矩阵非零元素: {nonzero:,}（双向）')
    except Exception as e:
        print(f'  ⚠️  同CpG岛矩阵构建失败（{e}），第4维全为0')

    # ── 边过滤：条件与原作者完全相同，不新增任何边 ──
    # 所有边都保证有共甲基化相关性支撑，PNA层可以正常工作
    src, dst = np.where(
        (
            ((chromosome_adj == 1) &
                ((np.abs(adj) > SECONDARY_THRESHOLD) |
                 ((abs(distance_matrix) < threshold_dist) & (np.abs(adj) > TERTIARY_THRESHOLD))
                )
            )
            | (np.abs(adj) > threshold_corr)
        )
        & (np.arange(adj.shape[0])[:, None] != np.arange(adj.shape[1]))
    )

    print('making edge weights.....')

    # ── 边权重：4维 ──
    # 维度1：共甲基化相关性（PNA学习的核心信号，所有边均有值）
    # 维度2：同染色体（0或1）
    # 维度3：同基因（0或1）
    # 维度4：同CpG岛标记（1.0=同岛，0.0=不同岛）
    weights = np.column_stack([
        adj[src, dst],               # 维度1：共甲基化相关性
        chromosome_adj[src, dst],    # 维度2：同染色体
        genes_adj[src, dst],         # 维度3：同基因
        same_island_adj[src, dst]    # 维度4：同CpG岛标记（新增）
    ])

    # 统计有同CpG岛标记的边数量
    island_labeled_edges = int(np.count_nonzero(same_island_adj[src, dst]))
    total_edges = len(src)
    print(f'  总边数: {total_edges:,}')
    print(f'  有同CpG岛标记的边: {island_labeled_edges:,} ({island_labeled_edges/total_edges*100:.2f}%)')

    edge_index = [torch.tensor(src, dtype=torch.int64), torch.tensor(dst, dtype=torch.int64)]
    edge_weight = weights
    edge_index = torch.stack(edge_index, dim=0)
    edge_attr = torch.tensor(edge_weight, dtype=torch.float32).reshape(-1, EDGE_DIM)
    print("shape of edge:", edge_index.shape)
    return edge_index, edge_attr


# compute_max_in_degree_and_histogram函数（与原始代码第523-561行一致）
def compute_max_in_degree_and_histogram(train_data_loader):
    """
    Compute the maximum in-degree and in-degree histogram tensor.
    """
    device_cpu = torch.device("cpu")

    max_degree = -1
    num_of_nodes = 0

    for idx, data in enumerate(train_data_loader):
        edge_index = data.edge_index[1].to(device_cpu)
        max_degree = max(max_degree, int(edge_index.max()))
        num_of_nodes += data.num_nodes
        if (idx + 1) % 100 == 0:
            print(f"Processed {idx + 1} batches, {num_of_nodes} nodes so far...")
        break

    deg = torch.zeros(max_degree + 1, dtype=torch.long, device=device_cpu)
    for idx, data in enumerate(train_data_loader.dataset):
        edge_index = data.edge_index[1].to(device_cpu)
        d = torch.bincount(edge_index, minlength=max_degree + 1).to(device_cpu)
        deg += d
        if (idx + 1) % 100 == 0:
            print(f"Processed {idx + 1} samples...")

    return max_degree, deg


# NODE_FEATURE_DICT（新增第10个特征：CpG岛密度）
NODE_FEATURE_DICT = {
    1: 'CPG_ISLAND',
    2: 'CPG_ISLAND_LEN',
    3: 'Distance_to_TSS',
    4: ["Next_Base_A", "Next_Base_C", "Next_Base_T"],
    5: 'start',
    6: 'end',
    7: 'Normalized_TSS_Coordinate',
    8: 'Normalized_MapInfo',
    9: [f'Chr_{x}' for x in range(1, 23)],
    10: 'island_density'   # 新增：该位点所在CpG岛内的位点密度（归一化）
}

# 特征选择：在原有"1,2,3,4,5,6,8"基础上加入第10个特征
selected_features = "1,2,3,4,5,6,8,10"
selected_feature_numbers = list(map(int, selected_features.split(',')))

user_selected_features = []
for key in selected_feature_numbers:
    feature = NODE_FEATURE_DICT[key]
    if isinstance(feature, list):
        user_selected_features.extend(feature)
    else:
        user_selected_features.append(feature)

INPUT_DIM = len(user_selected_features) + 1

print("Available features:")
for key, value in NODE_FEATURE_DICT.items():
    print(f"{key}: {value}")
print(f"\nUser selected features: {user_selected_features}")
print(f"INPUT_DIM: {INPUT_DIM}")
print("\n函数和参数定义完成！")

# ============================================================
# Cell 0-5: 加载甲基化数据并划分数据集
# ============================================================

# 加载AltumAge的CpG列表（与原始代码第307-308行一致）
AltumAge_cpgs = np.array(pd.read_pickle(
    '/data/projects/punim2698/yao14/graphage_seq/graph-age/example_dependencies/multi_platform_cpgs.pkl'
)).tolist()
print(f"AltumAge CpG数量: {len(AltumAge_cpgs)}")

# 数据选择函数（与原始代码第310-315行一致）
def select(d):
    a = d[d.columns[d.columns.isin(AltumAge_cpgs)].tolist() + ["age", 'gender', 'dataset', 'tissue_type']]
    b = a[a['tissue_type'].str.lower().str.contains('blood')].dropna()
    return b

# 加载数据（与原始代码第321-344行一致）
folder_paths = ['/data/projects/punim2698/yao14/graphage_seq/all-organs4/all_organs']

train_frames = []
test_frames = []
count = 0

for folder_path in folder_paths:
    for filename in os.listdir(folder_path):
        if filename.endswith(".pkl"):
            file_path = os.path.join(folder_path, filename)
            df = select(pd.read_pickle(file_path))
            if len(df) <= 0:
                continue
            count += len(df)
            train_df, test_df = train_test_split(df, test_size=0.2, random_state=42)
            train_frames.append(train_df)
            test_frames.append(test_df)

# 合并数据（与原始代码第347-348行一致）
train_combined = pd.concat(train_frames)
test_combined = pd.concat(test_frames)

# ── 40%子集采样（快速验证调控标记效果，验证有效后删除这两行改回全量）──
train_combined = train_combined.sample(frac=0.4, random_state=42)
test_combined  = test_combined.sample(frac=0.4, random_state=42)
print(f"[40%子集] 采样后 train={len(train_combined)}, test={len(test_combined)}")

# 划分训练集和验证集（与原始代码第351行一致）
train_data, val_data = train_test_split(train_combined, test_size=0.2, random_state=42)

print(f"总样本数: {count}")
print(f"训练集: {len(train_data)}")
print(f"验证集: {len(val_data)}")
print(f"测试集: {len(test_combined)}")

# 创建CpG到节点的映射（与原始代码第363行一致）
cpg2node = make_cpg2node(AltumAge_cpgs)

# 创建X和y（与原始代码第400-406行一致）
selected_columns = AltumAge_cpgs
X_train = train_data.drop(columns=["age", 'gender', 'dataset', 'tissue_type']).astype('float')
y_train = train_data.age
X_test = test_combined.drop(columns=["age", 'gender', 'dataset', 'tissue_type']).astype('float')
y_test = test_combined.age
X_val = val_data.drop(columns=["age", 'gender', 'dataset', 'tissue_type']).astype('float')
y_val = val_data.age

print(f"\nX_train形状: {X_train.shape}")
print(f"X_test形状: {X_test.shape}")
print(f"X_val形状: {X_val.shape}")

# 筛选information（与原始代码第439-440行一致）
filtered_information = information[information.IlmnID.isin(selected_columns)]
chromosomes = list(set(filtered_information.Chr))

# ── 新增：计算CpG岛密度特征（island_density）──
# 含义：该CpG位点所在CpG岛内共有多少个位点（归一化到0-1）
# 不在CpG岛内的位点 → 0.0
# 在CpG岛内的位点 → 该岛内的位点数 / 最大位点数
print("\n[新增特征] 计算CpG岛密度特征 island_density...")
from collections import Counter

island_locs = filtered_information['CPG_ISLAND_LOCATIONS'].values
# 统计每个CpG岛内有多少位点
island_size_counter = Counter(
    loc for loc in island_locs if pd.notna(loc) and str(loc).strip() != ''
)
# 最大岛密度（用于归一化）
max_island_size = max(island_size_counter.values()) if island_size_counter else 1

# 给每个位点赋值
island_density_values = np.array([
    island_size_counter.get(str(loc).strip(), 0) / max_island_size
    if pd.notna(loc) and str(loc).strip() != '' else 0.0
    for loc in island_locs
], dtype=np.float32)

# 加入filtered_information
filtered_information = filtered_information.copy()
filtered_information['island_density'] = island_density_values

# 打印统计信息
nonzero_count = (island_density_values > 0).sum()
print(f"  最大CpG岛密度（位点数）: {max_island_size}")
print(f"  在CpG岛内的位点数: {nonzero_count} ({nonzero_count/len(filtered_information)*100:.1f}%)")
print(f"  不在CpG岛内的位点数: {len(filtered_information)-nonzero_count}")
print(f"  island_density范围: {island_density_values.min():.3f} ~ {island_density_values.max():.3f}")
print(f"  island_density均值: {island_density_values.mean():.3f}")

# 其他变量（与原始代码第566-567行一致）
input_dimentions = INPUT_DIM
number_of_cpgs = len(selected_columns)

print(f"\nfiltered_information形状: {filtered_information.shape}")
print(f"染色体数量: {len(chromosomes)}")
print(f"number_of_cpgs: {number_of_cpgs}")
print(f"input_dimentions: {input_dimentions}")

print("\n数据加载完成！")

# ============================================================
# Cell 0-6: 验证所有变量是否存在
# ============================================================

print("验证所有必要变量...")
print("="*60)

# 变量检查
variables_check = {
    'information': information,
    'filtered_information': filtered_information,
    'AltumAge_cpgs': AltumAge_cpgs,
    'X_train': X_train,
    'y_train': y_train,
    'X_test': X_test,
    'y_test': y_test,
    'X_val': X_val,
    'y_val': y_val,
    'cpg2node': cpg2node,
    'chromosomes': chromosomes,
    'THRESHOLD_CORR': THRESHOLD_CORR,
    'THRESHOLD_DIST': THRESHOLD_DIST,
    'SECONDARY_THRESHOLD': SECONDARY_THRESHOLD,
    'TERTIARY_THRESHOLD': TERTIARY_THRESHOLD,
    'EDGE_DIM': EDGE_DIM,
    'user_selected_features': user_selected_features,
    'INPUT_DIM': INPUT_DIM,
    'input_dimentions': input_dimentions,
    'number_of_cpgs': number_of_cpgs,
}

all_exist = True
for name, var in variables_check.items():
    if var is not None:
        if isinstance(var, pd.DataFrame):
            print(f"✅ {name}: DataFrame {var.shape}")
        elif isinstance(var, pd.Series):
            print(f"✅ {name}: Series len={len(var)}")
        elif isinstance(var, list):
            print(f"✅ {name}: list len={len(var)}")
        elif isinstance(var, dict):
            print(f"✅ {name}: dict len={len(var)}")
        elif isinstance(var, (int, float)):
            print(f"✅ {name}: {var}")
        else:
            print(f"✅ {name}: {type(var).__name__}")
    else:
        print(f"❌ {name}: None")
        all_exist = False

# 函数检查
print("\n函数检查:")
print(f"✅ make_graph: {callable(make_graph)}")
print(f"✅ make_cpg2node: {callable(make_cpg2node)}")
print(f"✅ compute_max_in_degree_and_histogram: {callable(compute_max_in_degree_and_histogram)}")
print(f"✅ select: {callable(select)}")

# 检查TopGenomicSeq列是否存在
print(f"\n✅ TopGenomicSeq列存在: {'TopGenomicSeq' in filtered_information.columns}")

if all_exist:
    print("\n" + "="*60)
    print("✅ 所有变量验证通过！")
    print("="*60)
    print("\n下一步：运行 Cell 2-6（新增的模型代码），然后运行 Cell 7")
else:
    print("\n" + "="*60)
    print("❌ 部分变量缺失，请检查")
    print("="*60)

# ============================================================
# Cell 2: DNA序列预处理类（新增）
# ============================================================

class DNASequenceProcessor:
    """
    DNA序列预处理类

    功能：
    1. 从TopGenomicSeq列提取序列
    2. 将[CG]替换为CG
    3. One-Hot编码：A=[1,0,0,0], T=[0,1,0,0], C=[0,0,1,0], G=[0,0,0,1]
    """

    def __init__(self, max_seq_len=122):
        self.max_seq_len = max_seq_len
        self.nucleotide_to_idx = {'A': 0, 'T': 1, 'C': 2, 'G': 3}

    def process_single_sequence(self, seq):
        if pd.isna(seq) or not isinstance(seq, str) or len(seq) == 0:
            return np.zeros((self.max_seq_len, 4), dtype=np.float32)

        seq = seq.replace('[CG]', 'CG')
        seq = seq.upper()

        if len(seq) > self.max_seq_len:
            seq = seq[:self.max_seq_len]

        one_hot = np.zeros((self.max_seq_len, 4), dtype=np.float32)

        for i, nucleotide in enumerate(seq):
            if nucleotide in self.nucleotide_to_idx:
                one_hot[i, self.nucleotide_to_idx[nucleotide]] = 1.0
            else:
                one_hot[i, :] = 0.25

        return one_hot

    def process_all_sequences(self, sequences):
        all_one_hot = []
        for seq in tqdm(sequences, desc="Processing DNA sequences"):
            one_hot = self.process_single_sequence(seq)
            all_one_hot.append(one_hot)
        return np.array(all_one_hot, dtype=np.float32)
    def extract_statistical_features(self, seq):
        """从单条序列提取8维统计特征"""
        if pd.isna(seq) or not isinstance(seq, str) or len(seq) == 0:
          return np.zeros(8, dtype=np.float32)

        seq = seq.replace('[CG]', 'CG').upper()
        n = len(seq)

        # 1. 整体GC含量
        gc = (seq.count('G') + seq.count('C')) / max(n, 1)
        # 2. CpG密度
        cpg_count = seq.count('CG') / max(n - 1, 1)
        # 3. 上游GC含量（前60bp）
        upstream = seq[:60]
        gc_up = (upstream.count('G') + upstream.count('C')) / max(len(upstream), 1)
        # 4. 下游GC含量（后62bp之后）
        downstream = seq[62:]
        gc_down = (downstream.count('G') + downstream.count('C')) / max(len(downstream), 1)
        # 5-8. CpG位点周围10bp的碱基频率
        context = seq[55:65] if len(seq) >= 65 else seq
        a_freq = context.count('A') / max(len(context), 1)
        t_freq = context.count('T') / max(len(context), 1)
        c_freq = context.count('C') / max(len(context), 1)
        g_freq = context.count('G') / max(len(context), 1)

        return np.array([gc, cpg_count, gc_up, gc_down, a_freq, t_freq, c_freq, g_freq], dtype=np.float32)

    def extract_all_statistical_features(self, sequences):
        """批量提取统计特征，输出 [num_cpgs, 8]"""
        all_features = []
        for seq in tqdm(sequences, desc="Extracting sequence stats"):
            all_features.append(self.extract_statistical_features(seq))
        return np.array(all_features, dtype=np.float32)


# ============================================================
# 测试（使用filtered_information）
# ============================================================

print("测试 DNASequenceProcessor")
print("="*50)

processor = DNASequenceProcessor(max_seq_len=122)

# 测试单条序列
sample_seq = filtered_information['TopGenomicSeq'].iloc[0]
print(f"原始序列: {sample_seq[:60]}...")
print(f"原始长度: {len(sample_seq)}")

one_hot = processor.process_single_sequence(sample_seq)
print(f"\nOne-Hot编码形状: {one_hot.shape}")
print(f"前3个位置的编码:\n{one_hot[:3]}")

# 测试批量处理（前100条）
print("\n测试批量处理（前100条序列）...")
sample_sequences = filtered_information['TopGenomicSeq'].head(100).values
batch_one_hot = processor.process_all_sequences(sample_sequences)
print(f"批量处理后形状: {batch_one_hot.shape}")

if batch_one_hot.shape == (100, 122, 4):
    print("\n✅ DNASequenceProcessor 验证通过！")
else:
    print(f"\n❌ 形状错误，期望(100, 122, 4)，得到{batch_one_hot.shape}")

# ============================================================
# Cell 3: DNA序列编码器 - 1D CNN（新增）
# ============================================================

class DNASequenceEncoder(nn.Module):
    """
    DNA序列编码器 - 1D CNN

    架构：
    输入: [batch, seq_len, 4] (One-Hot编码)
    输出: [batch, embed_dim] (序列嵌入向量)

    使用多尺度卷积核捕获不同长度的序列模式：
    - kernel=3: 捕获3-mer模式（如CpG二核苷酸）
    - kernel=5: 捕获5-mer模式
    - kernel=7: 捕获更长的motif（如转录因子结合位点）
    """

    def __init__(self, seq_len=122, embed_dim=64):
        """
        参数：
        - seq_len: 输入序列长度
        - embed_dim: 输出嵌入维度
        """
        super(DNASequenceEncoder, self).__init__()

        self.seq_len = seq_len
        self.embed_dim = embed_dim

        # 第一层卷积：kernel_size=3
        self.conv1 = nn.Sequential(
            nn.Conv1d(in_channels=4, out_channels=32, kernel_size=3, padding=1),
            nn.BatchNorm1d(32),
            nn.ReLU()
        )

        # 第二层卷积：kernel_size=5
        self.conv2 = nn.Sequential(
            nn.Conv1d(in_channels=32, out_channels=64, kernel_size=5, padding=2),
            nn.BatchNorm1d(64),
            nn.ReLU()
        )

        # 第三层卷积：kernel_size=7
        self.conv3 = nn.Sequential(
            nn.Conv1d(in_channels=64, out_channels=128, kernel_size=7, padding=3),
            nn.BatchNorm1d(128),
            nn.ReLU()
        )

        # 全局最大池化
        self.global_max_pool = nn.AdaptiveMaxPool1d(1)

        # 全连接层：投影到嵌入维度
        self.fc = nn.Sequential(
            nn.Linear(128, embed_dim),
            nn.ReLU(),
            nn.Dropout(0.1)
        )

    def forward(self, x):
        """
        前向传播

        参数：
        - x: [batch, seq_len, 4]

        返回：
        - embeddings: [batch, embed_dim]
        """
        # 转置：[batch, seq_len, 4] -> [batch, 4, seq_len]
        x = x.permute(0, 2, 1)

        # 卷积层
        x = self.conv1(x)  # [batch, 32, seq_len]
        x = self.conv2(x)  # [batch, 64, seq_len]
        x = self.conv3(x)  # [batch, 128, seq_len]

        # 全局最大池化
        x = self.global_max_pool(x)  # [batch, 128, 1]
        x = x.squeeze(-1)  # [batch, 128]

        # 全连接层
        embeddings = self.fc(x)  # [batch, embed_dim]

        return embeddings


# ============================================================
# 测试代码
# ============================================================

print("测试 DNASequenceEncoder")
print("="*50)

# 创建编码器
encoder = DNASequenceEncoder(seq_len=122, embed_dim=64).to(device)

# 使用上一步处理好的batch_one_hot进行测试
# batch_one_hot 形状: (100, 122, 4)
test_input = torch.tensor(batch_one_hot, dtype=torch.float32).to(device)
print(f"输入形状: {test_input.shape}")

# 前向传播
with torch.no_grad():
    output = encoder(test_input)

print(f"输出形状: {output.shape}")
print(f"期望形状: (100, 64)")

# 查看输出的统计信息
print(f"\n输出统计:")
print(f"  均值: {output.mean().item():.4f}")
print(f"  标准差: {output.std().item():.4f}")
print(f"  最小值: {output.min().item():.4f}")
print(f"  最大值: {output.max().item():.4f}")

# 验证
if output.shape == (100, 64):
    print("\nDNASequenceEncoder 验证通过！")
else:
    print(f"\n形状错误，期望(100, 64)，得到{output.shape}")

# 打印模型参数量
total_params = sum(p.numel() for p in encoder.parameters())
print(f"\n模型参数量: {total_params:,}")

class HierarchicalNet(nn.Module):
    """
    方案二：Attention门控调制
    序列特征(常数，区分CpG位点) → 调制甲基化值的权重
    不做直接拼接，避免污染PNA
    """
    def __init__(self, deg, seq_len=122, original_dim=10, seq_embed_dim=8, num_cpgs=20000):
        super(HierarchicalNet, self).__init__()

        self.original_dim = original_dim

        # ===== 序列统计特征 → 甲基化重要性门控 =====
        # 序列特征决定"这个CpG位点的甲基化变化对年龄预测有多重要"
        self.importance_gate = nn.Sequential(
            nn.Linear(8, 16),
            nn.ReLU(),
            nn.Linear(16, 1),
            nn.Sigmoid()
        )

        # ===== 序列特征 → 2维位置附加信息 =====
        self.seq_proj = nn.Sequential(
            nn.Linear(8, 8),
            nn.ReLU(),
            nn.Linear(8, 2)
        )

        # PNA输入: 1(调制甲基化) + (original_dim-1)(原始位置特征) + 2(序列附加) = original_dim+2
        self.fused_dim = original_dim + 2  # = 12

        aggregators = ['mean', 'max', 'std', 'min']
        scalers = ['identity', 'amplification', 'attenuation']

        self.LastLayer = PNAConv(
            in_channels=self.fused_dim,
            out_channels=1,
            aggregators=aggregators,
            scalers=scalers,
            deg=deg,
            edge_dim=4,
            towers=1,
            pre_layers=1,
            post_layers=1,
            divide_input=False
        )

        self.mlp = nn.Sequential(
            nn.Linear(num_cpgs, 1024), nn.ReLU(),
            nn.Linear(1024, 656),      nn.SELU(),
            nn.Linear(656, 256),       nn.ReLU(),
            nn.Dropout(0.2),
            nn.Linear(256, 124),       nn.ReLU(),
            nn.Dropout(0.2),
            nn.Linear(124, 64),        nn.SELU(),
            nn.Linear(64, 32),         nn.ReLU(),
            nn.Linear(32, 8),          nn.ReLU(),
            nn.Linear(8, 1)
        )

    def forward(self, x_original, x_seq, edge_index, edge_attr, batch):
        """
        x_original: [num_nodes, original_dim]
                    第0列 = 甲基化值（样本间变化）
                    第1-9列 = 位置特征（CpG间变化，样本间不变）
        x_seq:      [num_nodes, 8]  序列统计特征（样本间不变，CpG间变化）
        """
        # 1. 序列特征生成门控权重，对甲基化值加权
        #    生物学含义：序列context决定该位点甲基化变化的预测重要性
        importance = self.importance_gate(x_seq)           # [num_nodes, 1]
        meth_modulated = x_original[:, 0:1] * importance  # [num_nodes, 1]

        # 2. 序列特征额外贡献2维附加信息（位置信息补充）
        seq_extra = self.seq_proj(x_seq)                   # [num_nodes, 2]

        # 3. 拼接：调制甲基化 + 原始位置特征(完全不动) + 序列附加
        x = torch.cat([
            meth_modulated,     # [num_nodes, 1]  含样本变化信息
            x_original[:, 1:], # [num_nodes, 9]  原始位置特征，梯度畅通
            seq_extra           # [num_nodes, 2]  序列位置补充
        ], dim=-1)              # → [num_nodes, 12]

        x = self.LastLayer(x, edge_index, edge_attr)
        x = F.relu(x)
        out = self.mlp(x.T)
        return out.flatten()


# 测试
print("测试 HierarchicalNet（方案二：Attention调制）")
num_cpgs_test = 1000
deg_test = torch.ones(5000, dtype=torch.long)

model_test = HierarchicalNet(
    deg=deg_test,
    seq_len=122,
    original_dim=INPUT_DIM,
    seq_embed_dim=8,
    num_cpgs=num_cpgs_test
).to(device)

x_original_test = torch.randn(num_cpgs_test, INPUT_DIM).to(device)
x_seq_test      = torch.randn(num_cpgs_test, 8).to(device)
src = torch.arange(0, num_cpgs_test - 1)
dst = torch.arange(1, num_cpgs_test)
edge_index_test = torch.stack([src, dst]).to(device)
edge_attr_test  = torch.randn(edge_index_test.shape[1], 4).to(device)
batch_test      = torch.zeros(num_cpgs_test, dtype=torch.long).to(device)

model_test.eval()
with torch.no_grad():
    output_test = model_test(x_original_test, x_seq_test, edge_index_test, edge_attr_test, batch_test)

seq_params = (sum(p.numel() for p in model_test.importance_gate.parameters()) +
              sum(p.numel() for p in model_test.seq_proj.parameters()))

print(f"PNA输入维度: {model_test.fused_dim}")   # 应为12
print(f"输出形状: {output_test.shape}")           # 应为torch.Size([1])
print(f"序列相关参数: {seq_params}")              # 应为很小的数字
print("✅ 验证通过！" if output_test.shape == torch.Size([1]) else "❌ 形状错误")

# ============================================================
# Cell 5: 修改后的DataLoader函数
# ============================================================

def data_loader_maker_hierarchical(X_, y_, edge_index, edge_attr,
                                    filtered_information, seq_data,
                                    user_selected_features, batch_size=1):
    """
    创建包含序列数据的DataLoader（修改版）

    与原始data_loader_maker的区别：
    - 新增参数 seq_data：预处理好的序列数据
    - Data对象新增 x_seq 字段

    参数：
    - X_: 甲基化数据 DataFrame [num_samples, num_cpgs]
    - y_: 年龄标签 Series [num_samples]
    - edge_index: 边索引 [2, num_edges]
    - edge_attr: 边属性 [num_edges, 3]
    - filtered_information: 筛选后的CpG信息 DataFrame
    - seq_data: 预处理好的序列数据 [num_cpgs, seq_len, 4]（新增）
    - user_selected_features: 选择的特征列名列表
    - batch_size: 批次大小

    返回：
    - DataLoader
    """
    current_graph = []

    # 将序列数据转换为tensor（所有样本共享同一套序列）
    seq_tensor = torch.tensor(seq_data, dtype=torch.float32)

    for row in range(len(X_)):
        # 原始特征处理（与原版相同）
        x = pd.concat([X_.iloc[row, :], filtered_information[user_selected_features]], axis=1, join='inner')
        x_original = torch.tensor(x.to_numpy().astype('float'), dtype=torch.float32)

        # 年龄标签
        y = torch.tensor(y_.iloc[row], dtype=torch.float32)

        # 创建图数据对象（新增x_seq字段）
        graph = Data(
            x=x_original,       # 原始节点特征 [num_cpgs, original_dim]
            x_seq=seq_tensor,   # 序列数据 [num_cpgs, seq_len, 4]（新增）
            y=y,
            edge_index=edge_index,
            edge_attr=edge_attr
        )
        current_graph.append(graph)

    return DataLoader(current_graph, batch_size=batch_size)


# ============================================================
# 测试代码（使用模拟数据）- 变量名已修改避免冲突
# ============================================================

print("测试 data_loader_maker_hierarchical")
print("="*50)

# 创建模拟数据
num_samples_mock = 5
num_cpgs_mock = 100

# 模拟甲基化数据
cpg_names_mock = [f"cg{i:08d}" for i in range(num_cpgs_mock)]
X_mock = pd.DataFrame(
    np.random.rand(num_samples_mock, num_cpgs_mock),
    columns=cpg_names_mock
)

# 模拟年龄标签
y_mock = pd.Series([25.0, 30.0, 45.0, 60.0, 75.0])

# 模拟CpG信息（只需要selected_features中的列）
user_selected_features_mock = ['CPG_ISLAND', 'Distance_to_TSS']
filtered_info_mock = pd.DataFrame({
    'CPG_ISLAND': np.random.randint(0, 2, num_cpgs_mock).astype(float),
    'Distance_to_TSS': np.random.rand(num_cpgs_mock)
}, index=cpg_names_mock)

# 模拟序列数据
# seq_data_mock = np.random.rand(num_cpgs_mock, 122, 4).astype(np.float32)
seq_data_mock = np.random.rand(num_cpgs_mock, 8).astype(np.float32)  # 改这里，122,4 → 8

# 模拟边
src_mock = torch.randint(0, num_cpgs_mock, (200,))
dst_mock = torch.randint(0, num_cpgs_mock, (200,))
edge_index_mock = torch.stack([src_mock, dst_mock], dim=0)
edge_attr_mock = torch.randn(200, 4)

print(f"模拟数据:")
print(f"  样本数: {num_samples_mock}")
print(f"  CpG数: {num_cpgs_mock}")
print(f"  X_mock形状: {X_mock.shape}")
print(f"  seq_data_mock形状: {seq_data_mock.shape}")

# 创建DataLoader
mock_loader = data_loader_maker_hierarchical(
    X_mock, y_mock,
    edge_index_mock, edge_attr_mock,
    filtered_info_mock, seq_data_mock,
    user_selected_features_mock,
    batch_size=1
)

print(f"\nDataLoader创建成功，共{len(mock_loader)}个批次")

# 检查一个批次的数据
for batch in mock_loader:
    print(f"\n单个批次的数据结构:")
    print(f"  batch.x 形状: {batch.x.shape}")
    print(f"  batch.x_seq 形状: {batch.x_seq.shape}")
    print(f"  batch.y 值: {batch.y.item():.1f}")
    print(f"  batch.edge_index 形状: {batch.edge_index.shape}")
    print(f"  batch.edge_attr 形状: {batch.edge_attr.shape}")
    break

# 验证
expected_feature_dim = 1 + len(user_selected_features_mock)  # 甲基化 + 选择的特征

print(f"\n期望 batch.x 形状: ({num_cpgs_mock}, {expected_feature_dim})")
print(f"期望 batch.x_seq 形状: ({num_cpgs_mock}, 8)")  # 改这里
if batch.x.shape == (num_cpgs_mock, expected_feature_dim) and batch.x_seq.shape == (num_cpgs_mock, 8):
      print("\n✅ data_loader_maker_hierarchical 验证通过！")
else:
    print("\n❌ 形状不匹配，请检查代码")

# ============================================================
# Cell 6: 修改后的训练和测试函数（加入绘图）
# ============================================================

def age_group(age):
    """年龄分组函数"""
    if age <= 0:
        return 0
    if age <= 20:
        return 1
    elif age <= 45:
        return 2
    elif age <= 55:
        return 3
    elif age <= 65:
        return 4
    elif age <= 75:
        return 5
    elif age <= 80:
        return 6
    else:
        return 7


def train_hierarchical(train_loader, model, optimizer, criterion, epoch, show_plot=True):
    """
    训练函数（修改版，加入绘图）
    """
    model.train()
    total_loss = 0
    truths = []
    predictions = []

    for data in tqdm(train_loader, total=len(train_loader), desc=f'Epoch {epoch}'):
        data = data.to(device)
        optimizer.zero_grad()

        # 前向传播（传入序列数据）
        out = model(data.x, data.x_seq, data.edge_index, data.edge_attr, data.batch)

        # 计算损失
        loss = criterion(out, data.y.flatten())

        truths.append(data.y.cpu().numpy())
        predictions.append(out.cpu().detach().numpy())

        # 反向传播
        loss.backward()
        optimizer.step()

        total_loss += loss.item() * len(data.y)

    average_loss = total_loss / len(train_loader.dataset)

    # 计算指标
    truths = np.array(truths).flatten()
    predictions = np.array(predictions).flatten()
    mae = mean_absolute_error(truths, predictions)
    mse = mean_squared_error(truths, predictions)
    r2 = r2_score(truths, predictions) if len(truths) > 1 else 0

    print(f'  Train - Loss: {average_loss:.4f}, MAE: {mae:.4f}, MSE: {mse:.4f}, R2: {r2:.4f}')

    # 绘制散点图
    if show_plot:
        plt.figure(figsize=(10, 5))
        plt.scatter(range(len(truths)), truths, color='blue', label='Truth', alpha=0.6, s=10)
        plt.scatter(range(len(predictions)), predictions, color='red', label='Pred', alpha=0.6, s=10)
        plt.xlabel('Sample Index')
        plt.ylabel('Age')
        plt.title(f'Train - Epoch {epoch}, Loss: {average_loss:.4f}, MAE: {mae:.4f}, MSE: {mse:.4f}, R2: {r2:.4f}\nTruth vs Prediction')
        plt.legend()
        plt.grid(True, alpha=0.3)
        plt.show()

    return average_loss, mae, mse, r2


@torch.no_grad()
def test_hierarchical(loader, model, criterion, epoch=None, show_plot=True):
    """
    测试函数（修改版，加入绘图和年龄组分析）
    """
    model.eval()
    total_error = 0
    truths = []
    predictions = []

    age_g_name = ['0', '0-20', '20-45', '45-55', '55-65', '65-75', '75-80', '80+']
    age_group_data = {i: {'truths': [], 'predictions': []} for i in range(8)}

    for data in tqdm(loader, total=len(loader), desc='Testing'):
        data = data.to(device)

        # 前向传播（传入序列数据）
        out = model(data.x, data.x_seq, data.edge_index, data.edge_attr, data.batch)

        truths.append(data.y.cpu().numpy())
        predictions.append(out.cpu().detach().numpy())
        total_error += (out - data.y).abs().sum().item()

    average_loss = total_error / len(loader.dataset)

    # 转换为数组
    truths = np.array(truths).flatten()
    predictions = np.array(predictions).flatten()

    # 按年龄组分类
    for truth, pred in zip(truths, predictions):
        group = age_group(truth)
        age_group_data[group]['truths'].append(truth)
        age_group_data[group]['predictions'].append(pred)

    # 计算各年龄组指标
    results = []
    for i in range(8):
        group_truths = np.array(age_group_data[i]['truths'])
        group_predictions = np.array(age_group_data[i]['predictions'])
        if len(group_truths) > 0:
            results.append({
                'Age Group': age_g_name[i],
                'MAE': mean_absolute_error(group_truths, group_predictions),
                'MSE': mean_squared_error(group_truths, group_predictions),
                'MedAE': median_absolute_error(group_truths, group_predictions),
                'R2': r2_score(group_truths, group_predictions) if len(group_truths) > 1 else 0,
                'num_sample': len(group_truths)
            })
        else:
            results.append({
                'Age Group': age_g_name[i],
                'MAE': None, 'MSE': None, 'MedAE': None, 'R2': None,
                'num_sample': 0
            })

    metrics_df = pd.DataFrame(results)

    # 计算总体指标
    mae = mean_absolute_error(truths, predictions)
    mse = mean_squared_error(truths, predictions)
    r2 = r2_score(truths, predictions) if len(truths) > 1 else 0

    print(f'  Test - MAE: {mae:.4f}, MSE: {mse:.4f}, R2: {r2:.4f}')

    # 绘制散点图
    if show_plot:
        plt.figure(figsize=(10, 5))
        plt.scatter(range(len(truths)), truths, color='blue', label='Truth', alpha=0.6, s=10)
        plt.scatter(range(len(predictions)), predictions, color='red', label='Pred', alpha=0.6, s=10)
        plt.xlabel('Sample Index')
        plt.ylabel('Age')
        plt.title(f'Test - Epoch {epoch}, Loss: {average_loss:.4f}, MAE: {mae:.4f}, MSE: {mse:.4f}, R2: {r2:.4f}\nTruth vs Prediction')
        plt.legend()
        plt.grid(True, alpha=0.3)
        plt.show()

    return mae, mse, r2, truths, predictions, metrics_df


@torch.no_grad()
def predict_hierarchical(loader, model):
    """
    预测函数（修改版）
    """
    model.eval()
    predictions = []

    for data in tqdm(loader, total=len(loader), desc='Predicting'):
        data = data.to(device)

        # 前向传播（传入序列数据）
        out = model(data.x, data.x_seq, data.edge_index, data.edge_attr, data.batch)
        predictions.append(out.cpu().detach().numpy())

    return np.array(predictions).flatten()


# ============================================================
# 测试代码
# ============================================================

print("✅ 训练/测试/预测函数定义完成！（已加入绘图功能）")

# ============================================================
# Cell 7: Cross-Validation 训练流程（对标原作者）
# ============================================================
#
# 与原作者的对应关系：
#   原作者 desired_fold=2, k=5  → 只训练第3折（index=2）
#   原作者 train_combined       → 你的 train_combined（已在Cell 0-5构建）
#   原作者 test_combined        → 你的 test_combined
#   原作者 make_graph           → 在折内用 fold 的 X_train 重新构建边
#   原作者保存条件              → val_loss < best AND test_loss < 5.5
#
# v2 修复：deg 存入 checkpoint，断点续训时直接复用，
#          避免重新计算 deg 与原始训练时不一致。

import os
import json

print("=" * 60)
print("Hierarchical GraphAge - Cross-Validation 训练")
print("=" * 60)

# ============================================================
# 步骤1：处理DNA序列数据（只需做一次，所有fold共享）
# ============================================================

print("\n[步骤1] 处理DNA序列数据...")

selected_sequences = filtered_information['TopGenomicSeq'].values
print(f"  CpG位点数量: {len(selected_sequences)}")

processor = DNASequenceProcessor(max_seq_len=122)
seq_data = processor.extract_all_statistical_features(selected_sequences)
print(f"  序列统计特征形状: {seq_data.shape}")  # (20318, 8)

# ============================================================
# 超参数（与原作者一致）
# ============================================================

param_grid = {
    'lr':           [0.5e-3 * (0.4 ** 2)],   # = 8e-5
    'weight_decay': [6e-4],
    'min_lr':       [1e-11],
    'patience':     [4],
    'factor':       [0.4],
}

NUM_EPOCHS   = 150
K_FOLDS      = 5
DESIRED_FOLD = 2          # 与原作者一致，只训练第3折（0-indexed）

# 检查点目录
CHECKPOINT_DIR = '/data/projects/punim2698/yao14/graphage_seq/checkpoint_islanddensity'
os.makedirs(CHECKPOINT_DIR, exist_ok=True)


# ============================================================
# 辅助函数：保存检查点（新增 deg 字段）
# ============================================================

def save_cv_checkpoint(path, model, optimizer, scheduler, epoch,
                       best_val_mae, best_test_mae, fold, params,
                       train_losses, val_maes, test_maes, deg):
    """
    保存检查点。
    deg 一并保存，确保断点续训时用的是同一份 deg，
    避免重新 compute_max_in_degree_and_histogram 时因样本顺序
    微小差异导致 deg 直方图不一致。
    """
    torch.save({
        'epoch':                epoch,
        'fold':                 fold,
        'params':               params,
        'model_state_dict':     model.state_dict(),
        'optimizer_state_dict': optimizer.state_dict(),
        'scheduler_state_dict': scheduler.state_dict(),
        'best_val_mae':         best_val_mae,
        'best_test_mae':        best_test_mae,
        'train_losses':         train_losses,
        'val_maes':             val_maes,
        'test_maes':            test_maes,
        'deg':                  deg,          # ← 新增
    }, path)


# ============================================================
# 辅助函数：加载检查点（新增 deg 返回值）
# ============================================================

def load_cv_checkpoint(path):
    """
    尝试加载检查点。
    返回：(ckpt_dict | None)
      - 若文件不存在，返回 None
      - 若存在，返回完整 ckpt 字典，由调用方决定如何使用

    调用方拿到 ckpt 后：
      1. 先用 ckpt['deg'] 创建模型
      2. 再调用 model.load_state_dict(ckpt['model_state_dict'])
    这样保证模型结构与保存时完全一致。
    """
    if not os.path.exists(path):
        print(f"  📂 未发现检查点，从头开始训练...")
        return None

    print(f"  📂 发现检查点: {path}")
    ckpt = torch.load(path, map_location=device)
    print(f"  ✅ 检查点读取成功")
    print(f"     保存时 Epoch:    {ckpt['epoch']}")
    print(f"     当前最佳 Val MAE:  {ckpt.get('best_val_mae', float('inf')):.4f}")
    print(f"     当前最佳 Test MAE: {ckpt.get('best_test_mae', float('inf')):.4f}")
    print(f"     已完成 {len(ckpt.get('train_losses', []))} 个 epoch")

    # 检查 deg 是否存在（兼容旧版本checkpoint）
    if 'deg' not in ckpt:
        print(f"  ⚠️  旧版检查点不含 deg，将重新计算 deg（正常现象，仅首次续训时出现）")

    return ckpt


# ============================================================
# Cross-Validation 主函数
# ============================================================

def cross_validation_training(param_grid, train_combined, test_combined,
                               seq_data, filtered_information,
                               num_epochs=150, k=5, desired_fold=2):
    """
    参数说明：
      param_grid           - 超参数网格（ParameterGrid）
      train_combined       - 全量训练数据 DataFrame（含 age/gender/dataset/tissue_type）
      test_combined        - 测试集 DataFrame
      seq_data             - 序列统计特征 np.ndarray [num_cpgs, 8]
      filtered_information - CpG位点信息 DataFrame
      num_epochs           - 训练轮数
      k                    - KFold 折数
      desired_fold         - 只训练哪一折（与原作者保持一致用 fold=2）
    """

    kf = KFold(n_splits=k, shuffle=True, random_state=42)
    data_array = train_combined    # KFold 在 train_combined 上划分

    for params in ParameterGrid(param_grid):

        print("\n" + "=" * 60)
        print(f"超参数: {params}")
        print("=" * 60)

        best_val_mae_global   = float('inf')
        best_model_state_dict = None

        for fold, (train_index, val_index) in enumerate(kf.split(data_array)):

            # ── 只训练指定的 fold（与原作者一致）──
            if fold != desired_fold:
                continue

            print(f"\n▶ Fold {fold + 1}/{k}  (train={len(train_index)}, val={len(val_index)})")

            # ── 检查点路径（按 fold 区分）──
            CKPT_PATH            = os.path.join(CHECKPOINT_DIR, f'cv_fold{fold}_checkpoint.pth')
            BEST_MODEL_PATH      = os.path.join(CHECKPOINT_DIR, f'cv_fold{fold}_best_model.pth')
            BEST_TEST_MODEL_PATH = os.path.join(CHECKPOINT_DIR, f'cv_fold{fold}_best_test_model.pth')

            # ── 提前尝试读取检查点，判断是否需要重建图 ──
            print("\n  [步骤2] 检查断点...")
            ckpt = load_cv_checkpoint(CKPT_PATH)
            resuming = (ckpt is not None)   # True = 断点续训，False = 从头训练

            # ── 划分本折数据 ──
            fold_train = data_array.iloc[train_index, :].sample(frac=1, random_state=42)
            fold_val   = data_array.iloc[val_index, :]

            X_fold_train = fold_train.drop(columns=["age", 'gender', 'dataset', 'tissue_type']).astype('float')
            y_fold_train = fold_train.age
            X_fold_val   = fold_val.drop(columns=["age", 'gender', 'dataset', 'tissue_type']).astype('float')
            y_fold_val   = fold_val.age
            X_fold_test  = test_combined.drop(columns=["age", 'gender', 'dataset', 'tissue_type']).astype('float')
            y_fold_test  = test_combined.age

            print(f"\n   Train: {len(X_fold_train)}  Val: {len(X_fold_val)}  Test: {len(X_fold_test)}")

            # ── 构建共甲基化图（始终基于本折训练集，无数据泄露）──
            print("\n  [步骤3] 构建共甲基化图（基于本折训练集）...")
            cur_edge_index, cur_edge_attr = make_graph(
                filtered_information, THRESHOLD_CORR, THRESHOLD_DIST,
                X_fold_train, cpg2node, chromosomes
            )
            print(f"  边数量: {cur_edge_index.shape[1]}")

            # ── 创建 DataLoader ──
            print("\n  [步骤4] 创建 DataLoader...")
            train_loader_h = data_loader_maker_hierarchical(
                X_fold_train, y_fold_train,
                cur_edge_index, cur_edge_attr,
                filtered_information, seq_data,
                user_selected_features, batch_size=1
            )
            val_loader_h = data_loader_maker_hierarchical(
                X_fold_val, y_fold_val,
                cur_edge_index, cur_edge_attr,
                filtered_information, seq_data,
                user_selected_features, batch_size=1
            )
            test_loader_h = data_loader_maker_hierarchical(
                X_fold_test, y_fold_test,
                cur_edge_index, cur_edge_attr,
                filtered_information, seq_data,
                user_selected_features, batch_size=1
            )
            print(f"  Train loader: {len(train_loader_h.dataset)} 样本")
            print(f"  Val loader:   {len(val_loader_h.dataset)} 样本")
            print(f"  Test loader:  {len(test_loader_h.dataset)} 样本")

            # ── 确定 deg：优先用 checkpoint 里保存的，否则重新计算 ──
            print("\n  [步骤5] 确定 deg（PNA 归一化统计量）...")
            if resuming and 'deg' in ckpt:
                # 关键修复：直接用保存时的 deg，保证 PNA 归一化与训练时完全一致
                deg = ckpt['deg'].to(torch.device('cpu'))
                max_degree = len(deg) - 1
                print(f"  ✅ 使用 checkpoint 中的 deg（max_degree={max_degree}），与初始训练完全一致")
            else:
                # 从头训练 或 旧版checkpoint没有deg → 重新计算
                max_degree, deg = compute_max_in_degree_and_histogram(train_loader_h)
                print(f"  ✅ 重新计算 deg（max_degree={max_degree}）")

            # ── 创建模型（使用确定好的 deg）──
            print("\n  [步骤6] 创建模型...")
            model_h = HierarchicalNet(
                deg=deg,
                seq_len=122,
                original_dim=INPUT_DIM,
                seq_embed_dim=8,
                num_cpgs=number_of_cpgs
            ).to(device)

            total_params = sum(p.numel() for p in model_h.parameters())
            print(f"  模型参数量: {total_params:,}  PNA输入维度: {model_h.fused_dim}")

            # ── 优化器 / 调度器 ──
            optimizer_h = torch.optim.Adam(
                model_h.parameters(),
                lr=params['lr'],
                weight_decay=params['weight_decay']
            )
            criterion_h = torch.nn.MSELoss()
            scheduler_h = ReduceLROnPlateau(
                optimizer_h, mode='min',
                factor=params['factor'],
                patience=params['patience'],
                min_lr=params['min_lr']
            )

            # ── 从 checkpoint 恢复权重、优化器、调度器状态 ──
            if resuming:
                try:
                    model_h.load_state_dict(ckpt['model_state_dict'])
                    optimizer_h.load_state_dict(ckpt['optimizer_state_dict'])
                    scheduler_h.load_state_dict(ckpt['scheduler_state_dict'])
                    start_epoch   = ckpt['epoch'] + 1
                    best_val_mae  = ckpt.get('best_val_mae',  float('inf'))
                    best_test_mae = ckpt.get('best_test_mae', float('inf'))
                    train_losses  = ckpt.get('train_losses',  [])
                    val_maes      = ckpt.get('val_maes',      [])
                    test_maes     = ckpt.get('test_maes',     [])
                    print(f"  ✅ 模型权重恢复成功，从 Epoch {start_epoch} 继续训练")
                except Exception as e:
                    print(f"  ⚠️  权重恢复失败（{e}），从头训练")
                    start_epoch   = 1
                    best_val_mae  = float('inf')
                    best_test_mae = float('inf')
                    train_losses  = []
                    val_maes      = []
                    test_maes     = []
            else:
                start_epoch   = 1
                best_val_mae  = float('inf')
                best_test_mae = float('inf')
                train_losses  = []
                val_maes      = []
                test_maes     = []

            # ── 训练循环 ──
            print(f"\n  开始训练: Epoch {start_epoch} → {num_epochs}")
            print("  " + "=" * 56)

            # ── CSV路径（训练开始前定义）──
            METRICS_CSV = os.path.join(CHECKPOINT_DIR, f'cv_fold{fold}_all_metrics.csv')
            # 从头训练时写表头；续训时追加（文件已存在则不重写表头）
            if not resuming or not os.path.exists(METRICS_CSV):
                with open(METRICS_CSV, 'w') as f:
                    f.write('epoch,lr,train_loss,train_mae,train_mse,train_r2,'
                            'val_mae,val_mse,val_r2,'
                            'test_mae,test_mse,test_r2\n')

            # best_test_mae 单独跟踪（不受 val 条件限制）
            best_test_mae_only = ckpt.get('best_test_mae_only', float('inf')) if resuming else float('inf')

            try:
                for epoch in range(start_epoch, num_epochs + 1):

                    # 训练
                    train_loss, train_mae, train_mse, train_r2 = train_hierarchical(
                        train_loader_h, model_h, optimizer_h, criterion_h,
                        epoch, show_plot=False
                    )
                    train_losses.append(train_loss)

                    # 验证 & 测试
                    val_mae, val_mse, val_r2, _, _, val_metrics_df = test_hierarchical(
                        val_loader_h, model_h, criterion_h, epoch, show_plot=False
                    )
                    test_mae, test_mse, test_r2, _, _, test_metrics_df = test_hierarchical(
                        test_loader_h, model_h, criterion_h, epoch, show_plot=False
                    )
                    val_maes.append(val_mae)
                    test_maes.append(test_mae)

                    # 学习率调度
                    scheduler_h.step(val_mae)
                    current_lr = optimizer_h.param_groups[0]['lr']

                    # ── 每个epoch追加写入CSV ──
                    with open(METRICS_CSV, 'a') as f:
                        f.write(f'{epoch},{current_lr:.2e},'
                                f'{train_loss:.6f},{train_mae:.6f},{train_mse:.6f},{train_r2:.6f},'
                                f'{val_mae:.6f},{val_mse:.6f},{val_r2:.6f},'
                                f'{test_mae:.6f},{test_mse:.6f},{test_r2:.6f}\n')

                    # ── 保存最佳val模型（val改善 且 test<5.5）──
                    if val_mae < best_val_mae and test_mae < 5.5:
                        best_val_mae  = val_mae
                        best_test_mae = test_mae
                        best_model_state_dict = model_h.state_dict()
                        torch.save(best_model_state_dict, BEST_MODEL_PATH)
                        print(f"\n  ★ 新最佳Val！Val MAE: {val_mae:.4f}  Test MAE: {test_mae:.4f}  (Epoch {epoch})")
                        val_metrics_df.to_csv(
                            os.path.join(CHECKPOINT_DIR, f'cv_fold{fold}_val_metrics.csv'), index=False
                        )
                        test_metrics_df.to_csv(
                            os.path.join(CHECKPOINT_DIR, f'cv_fold{fold}_test_metrics.csv'), index=False
                        )

                    # ── 保存最佳test模型（只看test_mae，不受val条件限制）──
                    if test_mae < best_test_mae_only:
                        best_test_mae_only = test_mae
                        torch.save(model_h.state_dict(), BEST_TEST_MODEL_PATH)
                        print(f"\n  ★ 新最佳Test！Test MAE: {test_mae:.4f}  (Epoch {epoch})")

                    print(f"  Epoch {epoch:03d}/{num_epochs} | LR: {current_lr:.2e} | "
                          f"Train: {train_loss:.4f} | Val MAE: {val_mae:.4f} | Test MAE: {test_mae:.4f}")

                    # ── 每 epoch 保存checkpoint（含 deg）──
                    save_cv_checkpoint(
                        CKPT_PATH, model_h, optimizer_h, scheduler_h, epoch,
                        best_val_mae, best_test_mae, fold, params,
                        train_losses, val_maes, test_maes,
                        deg
                    )

                    # 每10个epoch打印年龄组详情
                    if epoch % 10 == 0:
                        print("\n  验证集各年龄组:")
                        print(val_metrics_df.to_string(index=False))
                        print("\n  测试集各年龄组:")
                        print(test_metrics_df.to_string(index=False))

            except KeyboardInterrupt:
                print(f"\n  ⚠️  Fold {fold+1} 训练被中断，已保存检查点")
                print(f"     下次运行将从 Epoch {len(train_losses) + 1} 继续")

            # ── Fold 结束，绘制训练曲线 ──
            print(f"\n  Fold {fold+1} 训练完成！")
            print(f"  最佳 Val MAE:  {best_val_mae:.4f}")
            print(f"  最佳 Test MAE: {best_test_mae:.4f}")

            if train_losses:
                fig, axes = plt.subplots(1, 3, figsize=(15, 4))
                axes[0].plot(train_losses, 'b-'); axes[0].set_title('Train Loss');  axes[0].set_xlabel('Epoch')
                axes[1].plot(val_maes,     'g-'); axes[1].set_title('Val MAE');     axes[1].set_xlabel('Epoch')
                axes[2].plot(test_maes,    'r-'); axes[2].set_title('Test MAE');    axes[2].set_xlabel('Epoch')
                for ax in axes:
                    ax.grid(True)
                plt.tight_layout()
                plt.savefig(os.path.join(CHECKPOINT_DIR, f'cv_fold{fold}_training_curves.png'), dpi=150)
                plt.show()

        # ── 全局结果 ──
        print("\n" + "=" * 60)
        print(f"参数 {params} 训练完成")
        print(f"最佳 Val MAE:  {best_val_mae:.4f}")
        print(f"最佳 Test MAE: {best_test_mae:.4f}")
        print("=" * 60)


# ============================================================
# 启动训练
# ============================================================

cross_validation_training(
    param_grid           = param_grid,
    train_combined       = train_combined,
    test_combined        = test_combined,
    seq_data             = seq_data,
    filtered_information = filtered_information,
    num_epochs           = NUM_EPOCHS,
    k                    = K_FOLDS,
    desired_fold         = DESIRED_FOLD,
)

